using System;

namespace bioinformatics_stronghold
{
    public class RNA
    {
        public static string TranscribingDNAIntoRNA(string s)
        {
            var result = "";
            for (var i = 0; i < s.Length; i++)
            {
                switch (s.Substring(i, 1))
                {
                    case "A":
                        result += 'A';
                        break;
                    case "C":
                        result += 'C';
                        break;
                    case "G":
                        result += 'G';
                        break;
                    case "T":
                        result += 'U';
                        break;
                }
            }

            return result;
        }

        public static void Main(string[] args)
        {
            Console.WriteLine(TranscribingDNAIntoRNA(
                "TCGTATTCACAAGTGGTTGGCACGGCGGCTGGGGTATGTCTAAAACCTCATTGAGGGAGGTCTAGTGAGACAAATAGTATGAACCTATTACTACTAGCCCAAAAATACCCTGTGTCAAGCTGTGTGGACCTTATAGTAATTTCAAATGATAGCTTTCGTAGCCTCTCCTTTCAGTCAACCGTTAGTCGGATTGGGGGTACTGGTACACCACTTTATAAAGTTACCCTAGGATTAGCTTTGTGCGAAGAAGCGGACCATCTCATCCTCGAGAGGATCCTAGCGCCTGTCATGTACAAAGGTTGTTGGCTAAATCCCTATCAGCGGGCCCTCTACGAATTTAGGCGCATAGAGGCGAAGTATAAGTGGCTCTGATGATACTTGGTGGGAGTGGGGGGGAAATACGTAGGGTCGTCGGCATCGTCGCATGCTGAGAAACCTACGCTACCACGGATGACGGGCACAACGTAGATGAAGACGATTGACTCATGCAGCCCGGACGTTTCCGAATTCGGGCCGGCCATATCTCGTCCTATAGGAGTGCTTACAAGCGTGCACAAACTCGTTGCGCACGCGCGGACAACGCCCAAGCCGGTAAGACAATTAAACACTTGTGAATGTAATGTTACCAAGGGTCCACGAGTCCGCTAGCTTCCACAGGATTGTTACCGTTGCACGAACACCATCTTTAGCACAGAAGGGAGACCCATCCATACTTGGGAAAAGCTATATTTTTCCGAGACCAGGATGCCTTGTTGATAAGTAGGGTCTTCGATTTAATAGCATTGGGCGAATGCTCTCAGCTTGAGAGAGAGCCCCCTGCACCCATAAGGGGCAATCAGACAATAGCATGTGACACGGTCTTAGGACAGACCTTTCGATTGCTTTCGGCTGTCCCGGCACTATAGCACAATCAGACCGCAAGTCCTTAGAATTAATG"));

        }
    }
}